#The parameters for creating noise in tube_world sim
vx_mu: 0.0     #Gaussian noise mean for commanded twist tranlational speed
vx_std: 0.01    #Gaussian noise std for commanded twist tranlational speed
the_mu: 0.0    #Gaussian noise mean for commanded twist rotational speed
the_std: 0.01   #Gaussian noise std for commanded twist rotational speed
slip_min: 0.90  #Minimum slip noise
slip_max: 1.10  #Maximum slip noise
covar_sensor_x: 0.005  #The x component of covariance matrix for sensor
covar_sensor_y: 0.005  #The y component of covariance matrix for sensor
max_visible_dis: 0.7  #maximum distance beyond which tubes are not visible
range_std: 0.005 #Gaussian noise std for laser scan range 