#The parameters for the cardboard tubes in the sim world
tube_coor_x: [0.5, 0.8, 0.7, 0.2, 0.6, -0.3, -0.7, -0.3, -0.7]      #The x coordinates of the tubes
tube_coor_y: [0.0, 0.8, 0.4, -0.3, -0.8, -0.6, -0.2, 0.5, 0.7]      #The y coordinates of the tubes
tube_radius: 0.0762           #The radius of the tube
