#The parameters for the cardboard tubes in the sim world
tube_coor_x: [0.5, 0.3, -1.5, -1.1, -1.0, -0.7]      #The x coordinates of the tubes
tube_coor_y: [0.0, -0.5, 1.5, 1.3, -1.2, -0.9]      #The y coordinates of the tubes
tube_radius: 0.0762           #The radius of the tube
