#The parameters for the cardboard tubes in the sim world
tube_coor_x: [1.0, -1.0]      #The x coordinates of the tubes
tube_coor_y: [1.0, -1.0]      #The y coordinates of the tubes
tube_radius: 0.0762           #The radius of the tube
